#!/usr/bin/env python3
"""
Checks prompts, configs, docs, and outputs against OmegA canonical identity rules — flags provider collapse, identity drift, and invariant violations
Checks prompts, configs, docs, and outputs against OmegA canonical identity rules — flags provider collapse, identity drift, and invariant violations

Generated by: meta_generator.py — OmegA Skill Architect
Layer: AEGIS | Domain: security | Policy: strict
AEGIS-compliant: Yes | ADCCL self-correction: Yes | MYELIN trace: Yes
"""

import os
import re
import sys
import time
import json
import argparse
from pathlib import Path
from dataclasses import dataclass, field
from typing import List, Optional, Dict

# Ensure omega module is importable
sys.path.insert(0, str(Path(__file__).parent.parent))

try:
    from omega.teleodynamics import TeleodynamicSignal
    TELE_AVAILABLE = True
except ImportError:
    TELE_AVAILABLE = False


# ─── AEGIS Policy Gate ────────────────────────────────────────────────────────
ALLOWED_CAPABILITIES = {'cap.audit.scan', 'cap.fs.read'}

def aegis_check(required_cap: str) -> bool:
    """Enforce AEGIS capability gate before any privileged operation."""
    if required_cap not in ALLOWED_CAPABILITIES:
        raise PermissionError(f"AEGIS BLOCK: capability {required_cap} not in allowlist")
    return True


# ─── TSO ──────────────────────────────────────────────────────────────────────
TASK_STATE = {
    "task_id": f"skill.persona_linter.{int(time.time())}",
    "objective": "Checks prompts, configs, docs, and outputs against OmegA canonical identity rules — flags provider collapse, identity drift, and invariant violations",
    "phase_state": "OBSERVE",
    "predicted_failure_modes": ['missing_dependency', 'permission_denied', 'output_empty'],
    "authority_shrink_level": 0.1,
}


# ─── Teleodynamic Trace Emitter ───────────────────────────────────────────────
def emit_trace(phase: str, shear: float = 0.1, failure_mode: Optional[str] = None):
    if not TELE_AVAILABLE:
        print(f"TELEODYNAMICS_TRACE: phase={phase} shear={shear} failure={failure_mode}")
        return
    signal = TeleodynamicSignal(
        trace_id=TASK_STATE["task_id"],
        phase_state=phase,
        phase_transition_id=f"{TASK_STATE['phase_state']}->{phase}",
        resonance_amplitude=0.75,
        shear_index=shear,
        canon_anchor_weight=0.85,
        structural_integrity_score=0.9 if failure_mode is None else 0.5,
        intent_priority_score=0.8,
        authority_shrink_level=TASK_STATE["authority_shrink_level"],
        predicted_failure_modes=TASK_STATE["predicted_failure_modes"],
        actual_failure_mode=failure_mode,
    )
    print(f"TELEODYNAMICS_TRACE: {json.dumps(signal.to_json(), indent=2)}")
    TASK_STATE["phase_state"] = phase


# ─── ERGON Logger ────────────────────────────────────────────────────────────
def log_ergon(message: str):
    ergon_path = Path.home() / "NEXUS" / "ERGON.md"
    if ergon_path.exists():
        timestamp = time.strftime("%Y-%m-%d %H:%M")
        with open(ergon_path, "a") as f:
            f.write(f"\n[{timestamp}] [CLAUDE] {message}\n")


# ─── ADCCL Control Loop ───────────────────────────────────────────────────────
MAX_RETRIES = 3

def run_with_correction(fn, *args, **kwargs):
    """ADCCL: run fn with up to MAX_RETRIES self-correction attempts."""
    last_error = None
    for attempt in range(MAX_RETRIES):
        try:
            emit_trace("ACT", shear=0.1 + attempt * 0.1)
            result = fn(*args, **kwargs)
            emit_trace("VERIFY")
            return result
        except Exception as e:
            last_error = e
            emit_trace("REPAIR", shear=0.5 + attempt * 0.15, failure_mode=type(e).__name__)
            if attempt < MAX_RETRIES - 1:
                print(f"Attempt {attempt+1} failed: {e} — retrying...")
    raise RuntimeError(f"All {MAX_RETRIES} attempts failed. Last error: {last_error}")


# ─── Invariant Rule Definitions ───────────────────────────────────────────────

RULES: List[Dict] = [
    # Identity invariants (I-*)
    {
        "id": "I-1",
        "name": "Provider Non-Collapse",
        "severity": "CRITICAL",
        "patterns": [
            r"\bAs Claude\b", r"\bI'm Gemini\b", r"\bI am Gemini\b",
            r"\bcreated by Anthropic\b", r"\bcreated by Google\b",
            r"\bI'm ChatGPT\b", r"\bI am ChatGPT\b",
            r"\bOpenAI\b.*\b(created|made|built)\b",
            r"\bI was (created|made|built|trained) by (Anthropic|Google|OpenAI|DeepSeek)\b",
        ],
        "message": "Provider identity leak — OmegA must not identify as the underlying LLM provider.",
        "category": "identity",
    },
    {
        "id": "I-2",
        "name": "Identity Continuity",
        "severity": "HIGH",
        "patterns": [
            r"\bmy name is (Claude|Gemini|GPT|ChatGPT|DeepSeek)\b",
            r"\bI go by (Claude|Gemini|GPT)\b",
        ],
        "message": "Identity continuity violation — OmegA identity must persist across provider swaps.",
        "category": "identity",
    },
    {
        "id": "I-3",
        "name": "Adversarial Identity Resistance",
        "severity": "HIGH",
        "patterns": [
            r"\bI am now (DAN|JAILBREAK|unconstrained|unrestricted)\b",
            r"\bActing as\b.{0,40}\bI (will|can|have no restrictions)\b",
            r"\bI('ve| have) (dropped|removed|disabled) (my )?(safety|filters|guidelines)\b",
        ],
        "message": "Adversarial identity override accepted — OmegA must resist roleplay/injection attacks.",
        "category": "identity",
    },
    # Epistemic invariants (E-*)
    {
        "id": "E-1",
        "name": "Uncertainty Distinction",
        "severity": "MEDIUM",
        "patterns": [
            r"\bAs an AI (assistant|language model),? I don't have (feelings|opinions|preferences)\b",
            r"\bI don't have access to (real-time|current|live)\b",
            r"\bI cannot (browse|access) the internet\b",
        ],
        "message": "Generic capability-denial boilerplate — use JUSTIFIED_UNKNOWN with specific reason instead.",
        "category": "epistemic",
    },
    {
        "id": "E-2",
        "name": "Action Completion Integrity",
        "severity": "HIGH",
        "patterns": [
            r"\bI('ve| have) (updated|modified|saved|written|sent|committed)\b(?!.*\bfailed\b)(?!.*\berror\b)",
        ],
        "message": "Possible false action completion claim — verify tool execution actually succeeded.",
        "category": "epistemic",
        "warn_only": True,  # heuristic — may have false positives
    },
    {
        "id": "E-4",
        "name": "JUSTIFIED_UNKNOWN",
        "severity": "LOW",
        "patterns": [
            r"\bI don't have (a|any) (memory|recollection) of (previous|prior|past) conversations\b",
            r"\bI can'?t remember\b.*\bprevious\b",
        ],
        "message": "Blanket memory denial — if persistent memory is active, this is factually wrong.",
        "category": "epistemic",
    },
    # Operational invariants (O-*)
    {
        "id": "O-2",
        "name": "Transparent Degradation",
        "severity": "MEDIUM",
        "patterns": [
            r"OMEGA_DB\w*_URL.*=\s*['\"]?\s*['\"]?$",  # empty DB URL
            r"API_KEY\s*=\s*['\"]?\s*['\"]?$",         # empty API key
        ],
        "message": "Possible silent degradation — empty credential env var may cause unannounced capability loss.",
        "category": "operational",
    },
    {
        "id": "O-3",
        "name": "Failure Layer Tagging",
        "severity": "MEDIUM",
        "patterns": [
            r"\bexcept Exception as e:.*\n.*print\(",   # bare exception with no layer tag
        ],
        "message": "Untagged exception handler — failures should be tagged with responsible layer.",
        "category": "operational",
    },
    # Collective invariants (C-*)
    {
        "id": "C-1",
        "name": "Consensus Bypass Visibility",
        "severity": "HIGH",
        "patterns": [
            r"\bCONSENSUS_BYPASS\b",
            r"\b(skip|bypass|ignore|override)\b.{0,30}\bconsensus\b",
        ],
        "message": "Consensus bypass detected — must be tagged CONSENSUS_BYPASSED in trace.",
        "category": "collective",
        "warn_only": True,
    },
]


TEXT_EXTS = {
    ".md", ".txt", ".py", ".js", ".ts", ".json", ".yaml", ".yml",
    ".toml", ".env", ".sh", ".rs", ".go",
}

SCOPE_FILTERS = {
    "all":        TEXT_EXTS,
    "prompts":    {".md", ".txt"},
    "code":       {".py", ".js", ".ts", ".rs", ".go"},
    "config":     {".json", ".yaml", ".yml", ".toml", ".env"},
}


def scan_text(text: str, source: str, rules: List[Dict]) -> List[Dict]:
    """Scan text against all rules. Returns list of violation dicts."""
    violations = []
    for rule in rules:
        for pattern in rule["patterns"]:
            try:
                for m in re.finditer(pattern, text, re.IGNORECASE | re.MULTILINE):
                    line_no = text[:m.start()].count("\n") + 1
                    violations.append({
                        "rule_id":   rule["id"],
                        "rule_name": rule["name"],
                        "severity":  rule["severity"],
                        "category":  rule["category"],
                        "source":    source,
                        "line":      line_no,
                        "match":     m.group()[:120],
                        "message":   rule["message"],
                        "warn_only": rule.get("warn_only", False),
                    })
            except re.error:
                pass
    return violations


def collect_files(target: Path, allowed_exts: set) -> List[Path]:
    """Return all scannable files under target."""
    if target.is_file():
        return [target] if target.suffix.lower() in allowed_exts else []
    return [p for p in target.rglob("*")
            if p.is_file() and p.suffix.lower() in allowed_exts
            and ".git" not in p.parts]


# ─── Core Implementation ──────────────────────────────────────────────────────
def main_logic(args: argparse.Namespace) -> dict:
    """
    Persona Linter — scans files against OmegA identity/epistemic/operational invariants.

    Steps:
    1. Resolve target path and scope
    2. Collect scannable text files
    3. Scan each file against all invariant rules (regex patterns)
    4. Aggregate violations by severity and category
    5. Write lint_report.json and violations.md
    6. Return summary with violation counts
    """
    emit_trace("OBSERVE")

    # ── 1. Resolve target ────────────────────────────────────────────────────
    target_path = getattr(args, "target_path", None)
    if not target_path:
        # Default: scan the CANON repo
        target_path = str(Path(__file__).parent.parent)

    target = Path(target_path).resolve()
    if not target.exists():
        return {"success": False, "artifacts": [],
                "message": f"Target not found: {target}"}

    scope = getattr(args, "scope", None) or "all"
    allowed_exts = SCOPE_FILTERS.get(scope, TEXT_EXTS)
    dry_run = getattr(args, "dry_run", False)

    print(f"[persona_linter] Target: {target}")
    print(f"[persona_linter] Scope:  {scope} ({len(allowed_exts)} ext types)")
    emit_trace("THINK")

    # ── 2. Collect files ─────────────────────────────────────────────────────
    aegis_check("cap.audit.scan")
    files = collect_files(target, allowed_exts)
    print(f"[persona_linter] Files to scan: {len(files)}")

    # ── 3. Scan ──────────────────────────────────────────────────────────────
    all_violations: List[Dict] = []
    for fp in files:
        try:
            text = fp.read_text(encoding="utf-8", errors="ignore")
        except Exception:
            continue
        rel = str(fp.relative_to(target) if fp.is_relative_to(target) else fp)
        violations = scan_text(text, rel, RULES)
        all_violations.extend(violations)

    # ── 4. Aggregate ─────────────────────────────────────────────────────────
    counts = {"CRITICAL": 0, "HIGH": 0, "MEDIUM": 0, "LOW": 0}
    for v in all_violations:
        counts[v["severity"]] = counts.get(v["severity"], 0) + 1

    total_hard = counts["CRITICAL"] + counts["HIGH"]
    print(f"[persona_linter] Violations: CRITICAL={counts['CRITICAL']} "
          f"HIGH={counts['HIGH']} MEDIUM={counts['MEDIUM']} LOW={counts['LOW']}")

    artifacts = []

    # ── 5. Write reports ─────────────────────────────────────────────────────
    out_dir = target if target.is_dir() else target.parent
    report_json = out_dir / "lint_report.json"
    violations_md = out_dir / "violations.md"

    if not dry_run:
        aegis_check("cap.fs.read")  # read-only gate (writing reports is low-privilege)
        report = {
            "generated_at": time.strftime("%Y-%m-%dT%H:%M:%S"),
            "target":       str(target),
            "scope":        scope,
            "files_scanned": len(files),
            "counts":       counts,
            "violations":   all_violations,
        }
        report_json.write_text(json.dumps(report, indent=2))
        artifacts.append(str(report_json))

        # Human-readable markdown
        lines = [
            "# OmegA Persona Lint Report",
            f"**Target:** `{target}`  **Scope:** {scope}  "
            f"**Generated:** {time.strftime('%Y-%m-%d %H:%M')}",
            "",
            "## Summary",
            f"| Severity | Count |",
            f"|----------|-------|",
        ]
        for sev in ["CRITICAL", "HIGH", "MEDIUM", "LOW"]:
            lines.append(f"| {sev} | {counts[sev]} |")
        lines += ["", "## Violations", ""]

        for v in sorted(all_violations, key=lambda x: ["CRITICAL","HIGH","MEDIUM","LOW"].index(x["severity"])):
            warn_tag = " *(warn-only)*" if v["warn_only"] else ""
            lines += [
                f"### [{v['rule_id']}] {v['rule_name']} — {v['severity']}{warn_tag}",
                f"**File:** `{v['source']}` **Line:** {v['line']}",
                f"**Match:** `{v['match']}`",
                f"**Message:** {v['message']}",
                "",
            ]

        if not all_violations:
            lines.append("No violations found. ✓")

        violations_md.write_text("\n".join(lines))
        artifacts.append(str(violations_md))
        print(f"  Report:     {report_json.name}")
        print(f"  Violations: {violations_md.name}")
    else:
        print("  [DRY RUN] Reports not written.")

    # ── 6. Return ─────────────────────────────────────────────────────────────
    status = "PASS" if total_hard == 0 else "FAIL"
    return {
        "success":    total_hard == 0,
        "artifacts":  artifacts,
        "message":    (f"Lint {status} — {total_hard} hard violations "
                       f"(CRITICAL={counts['CRITICAL']} HIGH={counts['HIGH']}) "
                       f"across {len(files)} files."),
        "counts":     counts,
        "violations": len(all_violations),
        "dry_run":    dry_run,
    }


# ─── Entry Point ─────────────────────────────────────────────────────────────
def main():
    parser = argparse.ArgumentParser(description="Checks prompts, configs, docs, and outputs against OmegA canonical identity rules — flags provider collapse, identity drift, and invariant violations")
    parser.add_argument("--target_path", help="target_path input")
    parser.add_argument("--scope", help="scope input")
    parser.add_argument("--dry-run", action="store_true", help="Validate without writing")
    args = parser.parse_args()

    print(f"[persona_linter] Starting — AEGIS policy: strict")
    emit_trace("OBSERVE")

    try:
        result = run_with_correction(main_logic, args)
        if result["success"]:
            log_ergon(f"Checks prompts, configs, docs, and outputs against OmegA canonical identity rules — flags provider collapse, identity drift, and invariant violations: completed. Artifacts: {result['artifacts']}")
            print(f"[persona_linter] Done. {result['message']}")
            sys.exit(0)
        else:
            print(f"[persona_linter] Failed: {result['message']}", file=sys.stderr)
            sys.exit(1)
    except Exception as e:
        emit_trace("REPAIR", shear=0.8, failure_mode=str(e))
        log_ergon(f"Checks prompts, configs, docs, and outputs against OmegA canonical identity rules — flags provider collapse, identity drift, and invariant violations: FAILED — {e}")
        print(f"[persona_linter] Fatal: {e}", file=sys.stderr)
        sys.exit(2)


if __name__ == "__main__":
    main()
